import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])#2d array
print(" ")
print("2d array")
print(" ")
print(arr1)
print(" ")
#create array using zeros
print("zeros")
print(" ")
arr2=np.zeros(5)
print(arr2)
print(" ")
#create array using ones
print("ones")
print(" ")
arr3=np.ones(10)
print(arr3)
print(" ")
#create array using range
print("arange")
print(" ")
arr4=np.arange(10)
print(arr4)
arr5=np.arange(10,20)
print(arr5)
arr6=np.arange(10,20,2)
print(arr6)
print(" ")
#linspace()
print("linspace")
print(" ")
arr7=np.linspace(1,2,num=10)
print(arr7)
arr8=np.linspace(-1,1,num=15,endpoint=False)
print(arr8)
arr9=np.linspace(10,20,num=7,dtype=int)
print(arr9)
arr10,step=np.linspace(10,20,num=5,retstep=True)
print(arr10,step)